version: "3.7"
services:
  webserver:
    image: amazon/mwaa-local:2_9
    restart: always
    environment:
      - LOAD_EX=n
      - EXECUTOR=Sequential
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - "/Users/GarsiRW1/Documents/github/sdp-transformations/domains/sdp:/usr/local/airflow/dags"
      - "/Users/GarsiRW1/Documents/github/sdp-transformations/requirements:/usr/local/airflow/requirements"
      - "/Users/GarsiRW1/Documents/github/sdp-transformations/startup:/usr/local/airflow/startup"
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
